### ISSUE TITLE
设置背景图,导致文字无法居中

### ISSUE THREAD

**Issue by igding** [AndroidMsky/RandomTextView#3]
这个作为textview的背景图,我怎么样让每个数都居中?设置textscale的话,放大N倍 是可以达到居中的效果,但是文字样式就不好控制了,设置android:lineSpacingExtra和android:lineSpacingMultiplier 但是没有作用

**Comment by AndroidMsky** [comment]
我修改了绘制方式所以设置那些都没用，
两个解决办法。
1.写死控件高度而不是warp_content
2.控件下方再放一个显示背景的控件。

推荐1
