### ISSUE TITLE
drawText()这个方法为什么一直在调用，数字停止滚动后还在调；能否停止滚动后就停止绘制？

### ISSUE THREAD

**Issue by Lucas1012** [AndroidMsky/RandomTextView#4]

**Comment by AndroidMsky** [comment]
你是用的最新版的吗？ 应该不会的。你再看看

**Comment by Lucas1012** [comment]
我用的v1.3版试了，drawText()会一直调的，我用的log，一直在打印；

**Comment by Lucas1012** [comment]
我用的v1.3版试了，drawText()会一直调的，我用的log，一直在打印；

**Comment by Xiang0112** [comment]
同问。我这边也发现这个问题了，而且我这边如果数字里面有1，最后一个数字又不是1，最后一个数字会显示不完整，比如123，3就显示不完整
