### ISSUE TITLE
动画停止后一直绘制问题讨论

### ISSUE THREAD

**Issue by Lucas1012** [AndroidMsky/RandomTextView#5]
我用了一种方法，在drawNumber()里，                   
 if (auto == numLength * 2 - 1){
                        this.auto = false;
                        handler.removeCallbacks(task);
//加上如下判断，在结束延时动画后，不在调用绘制功能，可以解决动画停止后还一直绘制问题，
你看一下是否可行，或你的处理方式
                        if(this.auto){
                            invalidate();
                        }
                    }

**Comment by AndroidMsky** [comment]
我有在绘制结束时候修改auto的值，绘制就会停止

**Comment by Lucas1012** [comment]
修改auto的值Hander不会在循环执行，但是，我这边运行还是会重复绘制View，只有不让再调用绘制功能，后面才停止绘制，我这边试的结果是这样。

**Comment by AndroidMsky** [comment]
谢谢指出，确实存在问题，现在已经修复，一会发布1.4版本，thank you very much

**Comment by Lucas1012** [comment]
好的，多谢！
